spring:
  application:
    name: eureka-service
#pring.application.name=eureka-service
#erver.port=1111
#ureka.instance.hostname=localhost
#ureka.client.register-with-eureka=false
#ureka.client.fetch-registry=false
server:
  port: 1111
eureka:
  client:
    #它是用来管理服务的，所有不需要检索服务
    fetch-registry: false
    #是否向服务注册中心注册自己
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: localhost

#ureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/